app:
  telegram-token: ${telegram.token}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: classpath:token.properties

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
